### ISSUE TITLE
userDefaults: Unimplemented error in case with provided dependency value

### ISSUE THREAD

**Issue by arietis** [tgrapperon/swift-dependencies-additions#30] opened 2023-01-27 20:18 UTC
I'm not sure if it's a bug or I'm doing something wrong, but there is an equal chance to get the test passed or failed using this code:

```
final class ViewSpec: QuickSpec {
  // MARK: Spec

  override func spec() {
    describe("View") {
      let width = 320.0

      let height = 1000.0
      it("should match snapshots in dark mode") { @MainActor in
        withDependencies {
          $0.userDefaults = .liveValue
        } operation: {
          assertSnapshot(
            matching: View(screenWidth: width, previousView: String())
              .environment(\.colorScheme, .dark),
            as: .image(layout: .fixed(width: width, height: height)),
            named: "View.dark"
          )
        }
      }
      it("should match snapshots in light mode") { @MainActor in
        withDependencies {
          $0.userDefaults = .liveValue
        } operation: {
          assertSnapshot(
            matching: View(screenWidth: width, previousView: String())
              .environment(\.colorScheme, .light),
            as: .image(layout: .fixed(width: width, height: height)),
            named: "View.light"
          )
        }
      }
    }
  }
}

```
It always passes in dark mode but has a random chance of failing in light mode. 🤔
`Uncaught Exception: Unimplemented: @Dependency(\.userDefaults)`

**Comment by tgrapperon** [comment] 2023-01-27 21:16
Hey @arietis! This is weird indeed. My guess is that there is an escaping closure somewhere (in snapshot testing or in your own code) and the dependencies are reset. You can find more information about this phenomenon in the [documentation](https://pointfreeco.github.io/swift-dependencies/main/documentation/dependencies/lifetimes). In your case, `withEscapedDependencies` could help, but I'm not sure how to pass the escaped dependencies up to where it is used. Could you post a little more about `View`'s internals? Are you using a `StateObject`?

**Comment by tgrapperon** [comment] 2023-01-30 21:07
Great! I'll close the issue then. Feel free to reopen it if the problem is back!

**Closed by tgrapperon** 2023-01-30 21:07 UTC

**Comment by arietis** [comment] 2023-02-01 12:28
The root problem was similar to this one, I just need to prevent the app from loading in tests. https://github.com/pointfreeco/swift-dependencies/issues/37

**Comment by tgrapperon** [comment] 2023-02-01 12:52
Ah indeed, I missed this possibility! This behavior is extremely annoying. Maybe there are ways to improve its diagnostic because you're not the first, and definitely not the last to trip on it.
Thanks for the follow-up!

**Comment by JacksonUtsch** [comment] 2023-05-05 22:29
Hmm, I'm getting this same error even with the use of `if !_XCTIsTesting {`. I'll look to reproduce this in an isolated project.

**Comment by tgrapperon** [comment] 2023-05-06 01:49
Hey @JacksonUtsch! Make sure that you're not linking your test target with Dependencies. See testing section's last paragraph in the doc (on mobile right now)

**Comment by JacksonUtsch** [comment] 2023-05-06 12:50
It doesn't look like I have static linking. [Here](https://github.com/JacksonUtsch/App-Template/tree/debug/unimplemented) is a demo of the issue. 🤔

**Comment by tgrapperon** [comment] 2023-05-06 13:31
@JacksonUtsch, if you use the trailing closure to set your dependencies, it works:
```swift
let store = TestStore(
  initialState: ExampleFeature.State(),
  reducer: ExampleFeature()
) {
  $0.userDefaults = .ephemeral()
}
```
This is because this dependency fails as soon as you touch its test value, even if you don't call any endpoint. I did it like that because I was lazy and I didn't want to reimplement a complete failing one! I'll try to improve the situation soon.

**Comment by JacksonUtsch** [comment] 2023-05-06 13:41
Interesting.. I'm not sure how that is achieved when the dependency is overwritten. I'm guessing dependencies are iterated through internally in the TestStore or in Dependencies? And so the logic in result is different where you override.. 🤷

**Comment by tgrapperon** [comment] 2023-05-06 13:57
The trailing closure wraps everything internally in a `withDependencies`. This is the reducer modifier that is triggering it, but the value is already implemented when using the closure, so everything is fine then.
But this is rather a limitation of this specific dependency than a problem with the modifier.
